name: Continuous Delivery

on:
  push:
  workflow_dispatch:
    inputs:
      TESTS:
        description: "Run tests"
        required: false
        default: true
        type: choice
        options:
          - true
          - false

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        type:
        - coverage
        - terraform
    uses: ./.github/workflows/unit-tests.yml
    with:
      AWS_REGION: us-east-1
      DOCKER_IMAGE: python:3.11-slim
      RUN: ${{ inputs.TESTS }}
      TYPE: ${{ matrix.type }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  terraform_plan:
    if: ${{ github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name == 'main' }}
    name: Terraform plan
    strategy:
      fail-fast: false
      matrix:
        env:
        - ai-development
        - ai-production
        - ai-showroom
        - ai-staging
        - core-development
        - core-devops-sandbox
        - core-production
        - core-sandbox
        - core-showroom
        - core-staging
        - edge-development
        - edge-production
        - edge-showroom
        - edge-staging
        - infra-ai-development
        - infra-ai-production
        - infra-ai-staging
        - infra-development
        - infra-devops-sandbox
        - infra-edge-development
        - infra-edge-production
        - infra-edge-showroom
        - infra-edge-staging
        - infra-main-account
        - infra-production
        - infra-sandbox
        - infra-showroom
        - infra-staging
        - infra-system-development
        - infra-system-production
        - infra-system-sandbox
        - infra-system-staging
        - wallet-development
        - wallet-production
        - wallet-sandbox
        - wallet-showroom
        - wallet-staging
        region:
        - us-east-1
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  terraform_deploy:
    if: ${{ github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name == 'main' }}
    name: Terraform deploy
    strategy:
      fail-fast: false
      matrix:
        env:
        - ai-development
        - ai-production
        - ai-showroom
        - ai-staging
        - core-development
        - core-devops-sandbox
        - core-production
        - core-sandbox
        - core-showroom
        - core-staging
        - edge-development
        - edge-production
        - edge-showroom
        - edge-staging
        - infra-ai-development
        - infra-ai-production
        - infra-ai-staging
        - infra-development
        - infra-devops-sandbox
        - infra-edge-development
        - infra-edge-production
        - infra-edge-showroom
        - infra-edge-staging
        - infra-main-account
        - infra-production
        - infra-sandbox
        - infra-showroom
        - infra-staging
        - infra-system-development
        - infra-system-production
        - infra-system-sandbox
        - infra-system-staging
        - wallet-development
        - wallet-production
        - wallet-sandbox
        - wallet-showroom
        - wallet-staging
        region:
        - us-east-1
    needs:
    - terraform_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  create_release:
    runs-on: [ self-hosted, linux, intuitivo ]
    needs:
    - terraform_deploy
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release Notes
        id: release_notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod -R +x ./scripts
          ./scripts/release_notes.sh