name: Continuous Delivery

on:
  push:
  workflow_dispatch:
    inputs:
      TESTS:
        description: "Run tests"
        required: false
        default: true
        type: choice
        options:
          - true
          - false

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        type:
        - default
        - terraform
    uses: ./.github/workflows/unit-tests.yml
    with:
      AWS_REGION: us-east-1
      DOCKER_IMAGE: python:3.11-slim
      RUN: ${{ inputs.TESTS }}
      TYPE: ${{ matrix.type }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  terraform_plan:
    if: ${{ github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name == 'main' }}
    name: All accounts
    strategy:
      fail-fast: false
      matrix:
        env:
        - ai-development
        - ai-production
        - ai-staging
        - edge-development
        - edge-production
        - edge-showroom
        - edge-staging
        - infra-devops-sandbox
        - infra-showroom
        - system-development
        - system-production
        - system-sandbox
        - system-staging
        region:
        - us-east-1
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  terraform_deploy:
    if: ${{ github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name == 'main' }}
    name: All accounts
    strategy:
      fail-fast: false
      matrix:
        env:
        - ai-development
        - ai-production
        - ai-staging
        - edge-development
        - edge-production
        - edge-showroom
        - edge-staging
        - infra-devops-sandbox
        - infra-showroom
        - system-development
        - system-production
        - system-sandbox
        - system-staging
        region:
        - us-east-1
    needs:
    - all-accounts_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
