name: Set up ephemeral IAM role with policies

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: false
        type: string
        default: us-east-1
      ENVIRONMENT:
        required: true
        type: string
      TF_PATH:
        required: true
        type: string
        default: terraform
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    outputs:
      access_key_id:
        value: ${{ jobs.SetupEphemeralRole.outputs.access_key_id }}
      check_config_files:
        value: ${{ jobs.SetupEphemeralRole.outputs.check_config_files }}
      secret_access_key:
        value: ${{ jobs.SetupEphemeralRole.outputs.secret_access_key }}
      session_token:
        value: ${{ jobs.SetupEphemeralRole.outputs.session_token }}
env:
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  REGION: ${{ inputs.AWS_REGION }}
  VAR_FILE: ${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}

jobs:
  SetupEphemeralRole:
    runs-on: [ self-hosted, linux, intuitivo ]
    name: Set up ephemeral Role
    defaults:
      run:
        working-directory: ${{ inputs.TF_PATH }}
    outputs:
      aws_policies: ${{ steps.iam_policies.outputs.aws_policies }}
      access_key_id: ${{ steps.ephemeral_access.outputs.access_key_id }}
      check_config_files: ${{ steps.check-file.outputs.check_config_files }}
      secret_access_key: ${{ steps.ephemeral_access.outputs.secret_access_key }}
      session_token: ${{ steps.ephemeral_access.outputs.session_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Check Config Files
        id: check-file
        uses: intuitivo-ai/accessnator//actions/create-iam-roles@stable
        with:
          action: check-files
          tf_path: ${{ inputs.TF_PATH }}
      - name : Create ephemeral IAM Role
        if: ${{ steps.check-file.outputs.check_config_files }}
        id: ephemeral_access
        uses: intuitivo-ai/accessnator//actions/create-iam-roles@stable
        with:
          aws-region: ${{ inputs.AWS_REGION }}
          tf_path: ${{ inputs.TF_PATH }}
          squad: 
