name: Create IAM Policy
on:
  push:
    paths:
      - 'submodule/**'
  workflow_dispatch:
    inputs:
      ACTION:
        description: ''
        required: true
        default: plan
        type: choice
        options:
        - plan
        - deploy
      ENVIRONMENT:
        description: ''
        required: false
        default: infra-devops-sandbox
        type: choice
        options:
        - infra-devops-sandbox

jobs:
  infra-devops-sandbox_plan:
    if: ${{ inputs.ACTION && inputs.ENVIRONMENT == 'infra-devops-sandbox' }}
    name: Infra Devops-sandbox
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  infra-devops-sandbox_deploy:
    if: ${{ inputs.ACTION == 'deploy' && inputs.ENVIRONMENT == 'infra-devops-sandbox' }}
    name: Infra Devops-sandbox
    needs:
    - infra-devops-sandbox_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  all-accounts_plan:
    if: ${{ github.ref_type == 'branch' && github.event_name == 'push' }}
    name: All accounts
    strategy:
      fail-fast: false
      matrix:
        env:
        - ai-development
        - ai-production
        - ai-staging
        - edge-development
        - edge-production
        - edge-showroom
        - edge-staging
        - infra-devops-sandbox
        - infra-showroom
        - system-development
        - system-production
        - system-sandbox
        - system-staging
        region:
        - us-east-1
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  all-accounts_deploy:
    if: ${{ github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name == 'main' }}
    name: All accounts
    strategy:
      fail-fast: false
      matrix:
        env:
        - ai-development
        - ai-production
        - ai-staging
        - edge-development
        - edge-production
        - edge-showroom
        - edge-staging
        - infra-devops-sandbox
        - infra-showroom
        - system-development
        - system-production
        - system-sandbox
        - system-staging
        region:
        - us-east-1
    needs:
    - all-accounts_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
