name: Pull Request
on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  terraform_plan:
    if: ${{ !github.event.pull_request.draft  }}
    name: Terraform plan
    strategy:
      fail-fast: false
      matrix:
        env:
        - ai-development
        - ai-production
        - ai-showroom
        - ai-staging
        - core-development
        - core-devops-sandbox
        - core-production
        - core-sandbox
        - core-showroom
        - core-staging
        - edge-development
        - edge-production
        - edge-showroom
        - edge-staging
        - infra-ai-development
        - infra-ai-production
        - infra-ai-staging
        - infra-development
        - infra-devops-sandbox
        - infra-edge-development
        - infra-edge-production
        - infra-edge-showroom
        - infra-edge-staging
        - infra-main-account
        - infra-production
        - infra-sandbox
        - infra-showroom
        - infra-staging
        - infra-system-development
        - infra-system-production
        - infra-system-sandbox
        - infra-system-staging
        - wallet-development
        - wallet-production
        - wallet-sandbox
        - wallet-showroom
        - wallet-staging
        region:
        - us-east-1
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}