name: Pull Request
on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  terraform_plan:
    if: ${{ !github.event.pull_request.draft  }}
    name: Terraform plan
    strategy:
      fail-fast: false
      matrix:
        env:
        - ai-development
        - ai-production
        - ai-staging
        - edge-development
        - edge-production
        - edge-showroom
        - edge-staging
        - infra-devops-sandbox
        - infra-showroom
        - system-development
        - system-production
        - system-sandbox
        - system-staging
        region:
        - us-east-1
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: submodule
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}